# Generated by Django 4.0.2 on 2022-07-05 19:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country_to_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=1023)),
                ('address2', models.CharField(max_length=1023)),
                ('city', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.countries')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.country_to_state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1023)),
                ('brand', models.CharField(max_length=255)),
                ('market_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('image', models.ImageField(max_length=1024, upload_to='static/product/')),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=102400)),
                ('size_1', models.BooleanField()),
                ('size_2', models.BooleanField()),
                ('size_3', models.BooleanField()),
                ('size_4', models.BooleanField()),
                ('size_5', models.BooleanField()),
                ('size_6', models.BooleanField()),
                ('size_7', models.BooleanField(default=False)),
                ('size_8', models.BooleanField(default=False)),
                ('size_9', models.BooleanField(default=False)),
                ('size_10', models.BooleanField(default=False)),
                ('size_11', models.BooleanField(default=False)),
                ('size_12', models.BooleanField(default=False)),
                ('size_13', models.BooleanField(default=False)),
                ('size_14', models.BooleanField(default=False)),
                ('size_15', models.BooleanField(default=False)),
                ('size_1_quantity', models.IntegerField()),
                ('size_2_quantity', models.IntegerField()),
                ('size_3_quantity', models.IntegerField()),
                ('size_4_quantity', models.IntegerField()),
                ('size_5_quantity', models.IntegerField()),
                ('size_6_quantity', models.IntegerField()),
                ('size_7_quantity', models.IntegerField(default=-1)),
                ('size_8_quantity', models.IntegerField(default=-1)),
                ('size_9_quantity', models.IntegerField(default=-1)),
                ('size_10_quantity', models.IntegerField(default=-1)),
                ('size_11_quantity', models.IntegerField(default=-1)),
                ('size_12_quantity', models.IntegerField(default=-1)),
                ('size_13_quantity', models.IntegerField(default=-1)),
                ('size_14_quantity', models.IntegerField(default=-1)),
                ('size_15_quantity', models.IntegerField(default=-1)),
                ('size_1_quantity_sold', models.IntegerField()),
                ('size_2_quantity_sold', models.IntegerField()),
                ('size_3_quantity_sold', models.IntegerField()),
                ('size_4_quantity_sold', models.IntegerField()),
                ('size_5_quantity_sold', models.IntegerField()),
                ('size_6_quantity_sold', models.IntegerField()),
                ('size_7_quantity_sold', models.IntegerField(default=-1)),
                ('size_8_quantity_sold', models.IntegerField(default=-1)),
                ('size_9_quantity_sold', models.IntegerField(default=-1)),
                ('size_10_quantity_sold', models.IntegerField(default=-1)),
                ('size_11_quantity_sold', models.IntegerField(default=-1)),
                ('size_12_quantity_sold', models.IntegerField(default=-1)),
                ('size_13_quantity_sold', models.IntegerField(default=-1)),
                ('size_14_quantity_sold', models.IntegerField(default=-1)),
                ('size_15_quantity_sold', models.IntegerField(default=-1)),
                ('total_quantity_sold', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('brand', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 7, 6, 1, 7, 31, 359581))),
                ('status', models.CharField(max_length=255)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer_model')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'product_id')},
            },
        ),
    ]
