# Generated by Django 4.0.2 on 2022-07-05 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 1, 7, 55, 357538)),
        ),
    ]
