# Generated by Django 4.0.2 on 2022-07-11 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_orders_timestamp_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 10, 42, 24, 464285)),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(max_length=1024, upload_to='media_root/static/product/'),
        ),
    ]
